
workspace 'TuSDKFPDemo'

target 'TuSDKDemo' do
  
  xcodeproj 'TuSDKDemo.xcodeproj'
  workspace 'TuSDKFPDemo'
#    pod 'DoraemonKit/Core', '~> 3.0.4', :configurations => ['Debug']
    pod 'SSZipArchive', '2.4.2'
end
